### PR TITLE
Add a deprecation notice to the README

### PR DESCRIPTION
**Pull request by j-f1**

### CODE REVIEW

**Review by taion — APPROVED** [review]

**Review by patrick91 — APPROVED** [review]
I still hope we do finish this, but yes, let's mark as deprecated :)

**Comment by bd82** [comment]
😭

**Comment by hawkins** [comment]
Is this deprecated because the project's over or because you don't want users to use it while it's unstable?

**Comment by j-f1** [comment]
Because the project isn’t really maintained anymore.

**Pull request merged**
